const tasks = [
    {
        clientName: 'Client Name',
        clientImg: 'clientIMG.jpg',
        supervisorName: 'Sadik Istiak',
        supervisorImg: 'supervisorIMG.jpg',
        taskSummary: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur velit nemo accusamus. Dolorum, doloribus quisquam unde repellat iusto voluptatum quasi?',
        progress: '1/2',
        staff1Img: 'staff1.jpg',
        staff2Img: 'staff2.jpg',
        modules: 12,
        message: 15,
        attachment: 25,
        date: '30-12-2022'
    },
    {
        clientName: 'Client Name',
        clientImg: 'clientIMG.jpg',
        supervisorName: 'Sadik Istiak',
        supervisorImg: 'supervisorIMG.jpg',
        taskSummary: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur velit nemo accusamus. Dolorum, doloribus quisquam unde repellat iusto voluptatum quasi?',
        progress: '1/2',
        staff1Img: 'staff1.jpg',
        staff2Img: 'staff2.jpg',
        modules: 12,
        message: 15,
        attachment: 25,
        date: '30-12-2022'
    },
    {
        clientName: 'Client Name',
        clientImg: 'clientIMG.jpg',
        supervisorName: 'Sadik Istiak',
        supervisorImg: 'supervisorIMG.jpg',
        taskSummary: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur velit nemo accusamus. Dolorum, doloribus quisquam unde repellat iusto voluptatum quasi?',
        progress: '1/2',
        staff1Img: 'staff1.jpg',
        staff2Img: 'staff2.jpg',
        modules: 12,
        message: 15,
        attachment: 25,
        date: '30-12-2022'
    },
    {
        clientName: 'Client Name',
        clientImg: 'clientIMG.jpg',
        supervisorName: 'Sadik Istiak',
        supervisorImg: 'supervisorIMG.jpg',
        taskSummary: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur velit nemo accusamus. Dolorum, doloribus quisquam unde repellat iusto voluptatum quasi?',
        progress: '1/2',
        staff1Img: 'staff1.jpg',
        staff2Img: 'staff2.jpg',
        modules: 12,
        message: 15,
        attachment: 25,
        date: '30-12-2022'
    },
    {
        clientName: 'Client Name',
        clientImg: 'clientIMG.jpg',
        supervisorName: 'Sadik Istiak',
        supervisorImg: 'supervisorIMG.jpg',
        taskSummary: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur velit nemo accusamus. Dolorum, doloribus quisquam unde repellat iusto voluptatum quasi?',
        progress: '1/2',
        staff1Img: 'staff1.jpg',
        staff2Img: 'staff2.jpg',
        modules: 12,
        message: 15,
        attachment: 25,
        date: '30-12-2022'
    },
    {
        clientName: 'Client Name',
        clientImg: 'clientIMG.jpg',
        supervisorName: 'Sadik Istiak',
        supervisorImg: 'supervisorIMG.jpg',
        taskSummary: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur velit nemo accusamus. Dolorum, doloribus quisquam unde repellat iusto voluptatum quasi?',
        progress: '1/2',
        staff1Img: 'staff1.jpg',
        staff2Img: 'staff2.jpg',
        modules: 12,
        message: 15,
        attachment: 25,
        date: '30-12-2022'
    },
    {
        clientName: 'Client Name',
        clientImg: 'clientIMG.jpg',
        supervisorName: 'Sadik Istiak',
        supervisorImg: 'supervisorIMG.jpg',
        taskSummary: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur velit nemo accusamus. Dolorum, doloribus quisquam unde repellat iusto voluptatum quasi?',
        progress: '1/2',
        staff1Img: 'staff1.jpg',
        staff2Img: 'staff2.jpg',
        modules: 12,
        message: 15,
        attachment: 25,
        date: '30-12-2022'
    },
    {
        clientName: 'Client Name',
        clientImg: 'clientIMG.jpg',
        supervisorName: 'Sadik Istiak',
        supervisorImg: 'supervisorIMG.jpg',
        taskSummary: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur velit nemo accusamus. Dolorum, doloribus quisquam unde repellat iusto voluptatum quasi?',
        progress: '1/2',
        staff1Img: 'staff1.jpg',
        staff2Img: 'staff2.jpg',
        modules: 12,
        message: 15,
        attachment: 25,
        date: '30-12-2022'
    },
    {
        clientName: 'Client Name',
        clientImg: 'clientIMG.jpg',
        supervisorName: 'Sadik Istiak',
        supervisorImg: 'supervisorIMG.jpg',
        taskSummary: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur velit nemo accusamus. Dolorum, doloribus quisquam unde repellat iusto voluptatum quasi?',
        progress: '1/2',
        staff1Img: 'staff1.jpg',
        staff2Img: 'staff2.jpg',
        modules: 12,
        message: 15,
        attachment: 25,
        date: '30-12-2022'
    },
    {
        clientName: 'Client Name',
        clientImg: 'clientIMG.jpg',
        supervisorName: 'Sadik Istiak',
        supervisorImg: 'supervisorIMG.jpg',
        taskSummary: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur velit nemo accusamus. Dolorum, doloribus quisquam unde repellat iusto voluptatum quasi?',
        progress: '1/2',
        staff1Img: 'staff1.jpg',
        staff2Img: 'staff2.jpg',
        modules: 12,
        message: 15,
        attachment: 25,
        date: '30-12-2022'
    },
]

console.log(tasks);